version: 2.0
references:
  docker_images: &docker_images
    - image: circleci/slim-base

  working_directory: &working_directory
    working_directory: ~/src

jobs:
  test:
    docker: *docker_images

    <<: *working_directory

    steps:
      - checkout

      - run: for i in `seq 1 100`; do echo $i; done

      - run: mkdir test && date > test/date.txt

      - store_artifacts:
          path: test

  deploy:
    docker: *docker_images

    <<: *working_directory

    steps:
      - run: env

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          context: org-global
          requires:
            - test

experimental:
  notify:
    branches:
      only:
        - master
